### PR TITLE
Being able to load a schema manually

### PR DESCRIPTION
**Pull request by daycry**
- Being able to load a schema manually

### CODE REVIEW

**Comment by MGatner** [comment]
The `Schemas` library can already take a manually-loaded Schema, which would in turn be used by `Relations`: https://github.com/tattersoftware/codeigniter4-schemas/blob/cee97dbe49fe5d7ce57b756bc1f61500017db13d/src/Schemas.php#L85

I would need to hear a strong supporting case on why an individual Model/Entity should use its own manually-provided Schema before approving this.

**Comment by daycry** [comment]
But the vendor relations, collects the data by querying the database,
and does not allow the model to be loaded manually to avoid calls to
the database.

With the change I propose you can load the model, for example, through
directory instead of using the $chemas->get() function, used in the
Base trait.

**Comment by MGatner** [comment]
That all makes sense, but you can still accomplish the same thing using Schemas. If you call `service('schemas')->setSchema($schema)` with the same input that you would pass into your `BaseEntity::setSchema()` it will use that schema instead of loading from the database. I'm trying to find out how someone would use your new method instead did the existing one. Introducing a "local schema" for a model or entity opens up a can of worms and could be very confusing.

**Comment by daycry** [comment]
For example, if I use a UserModel() With relations, when you call a find()
funtion It call $schemas->get(), and every model that use relations trait
Will call the same function another time. If we can call setSchema like
this:
$schema= (new DirectoryHandler())->draft();
$userModel->setSchema($schema)->with(`keys`)->find(); you can avoid call
schema->get() on the fly.

I think that is an interesting feature, for my proyects is usefull when I
work with a lot of databases in the same proyect.

**Comment by MGatner** [comment]
So is the issue that you have multiple databases and you need to be able to enforce a specific database's schema on a model? 

I don't think calling `$schemas->get()` is really a performance concern. After the schema is loaded initially this will just be a simple property fetch from the library class. By "injecting" local schemas you're gaining a tiny performance boost in exchange for the extra memory, which can grow rather large depending on how complex your schema is.

**Comment by daycry** [comment]
Yes, exacly.

This is the issue, directoryHandler is an example I prefer use
DatabaseHandler and save It on redis.

But relations can't work with differents databases I proposed this feature,
because I can't said the group of database that I want work in the
relations library.

**Comment by daycry** [comment]
For example:

[image: image.png]

In this example I get the schema with schemas library and I set the schema
variable in relation library.

It works with my changes.

**Comment by MGatner** [comment]
Your image didn't come through. 

I am beginning to see your issue, but it still doesn't make me think this is a good change for the library. You could implement this yourself on a `BaseModel` and use it throughout your project. I don't want to promote a solution that creates multiple instance-specific Schemas; I think the official fix for this is to improve multiple-database handling in `Tatter\Schemas`.

**Comment by daycry** [comment]
Ok,

Thank you for tour attention. I Will do a fork with my changes as a
workarround, but I Will think how I can help us with multi-databases issue
when I finish my active projects.

Thank you so much.

**Pull request closed without merging**
